<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://Argix" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://Argix" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://Argix/Imports">
      <xsd:import schemaLocation="http://localhost:53791/Argix10.Enterprise.Services/FastTracking.svc?xsd=xsd0" namespace="http://Argix" />
      <xsd:import schemaLocation="http://localhost:53791/Argix10.Enterprise.Services/FastTracking.svc?xsd=xsd3" namespace="http://schemas.datacontract.org/2004/07/Argix" />
      <xsd:import schemaLocation="http://localhost:53791/Argix10.Enterprise.Services/FastTracking.svc?xsd=xsd1" namespace="http://schemas.microsoft.com/2003/10/Serialization/" />
      <xsd:import schemaLocation="http://localhost:53791/Argix10.Enterprise.Services/FastTracking.svc?xsd=xsd2" namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="IFastTrackingService_TrackCartons_InputMessage">
    <wsdl:part name="parameters" element="tns:TrackCartons" />
  </wsdl:message>
  <wsdl:message name="IFastTrackingService_TrackCartons_OutputMessage">
    <wsdl:part name="parameters" element="tns:TrackCartonsResponse" />
  </wsdl:message>
  <wsdl:message name="IFastTrackingService_TrackCartons_ConfigurationFaultFault_FaultMessage">
    <wsdl:part xmlns:q1="http://schemas.datacontract.org/2004/07/Argix" name="detail" element="q1:ConfigurationFault" />
  </wsdl:message>
  <wsdl:portType name="IFastTrackingService">
    <wsdl:operation name="TrackCartons">
      <wsdl:input wsaw:Action="http://Argix/IFastTrackingService/TrackCartons" message="tns:IFastTrackingService_TrackCartons_InputMessage" />
      <wsdl:output wsaw:Action="http://Argix/IFastTrackingService/TrackCartonsResponse" message="tns:IFastTrackingService_TrackCartons_OutputMessage" />
      <wsdl:fault wsaw:Action="http://Argix.TrackingFault" name="ConfigurationFaultFault" message="tns:IFastTrackingService_TrackCartons_ConfigurationFaultFault_FaultMessage" />
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>