//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argix.HR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceInfo", Namespace="http://schemas.datacontract.org/2004/07/Argix")]
    [System.SerializableAttribute()]
    public partial class ServiceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TerminalIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Connection {
            get {
                return this.ConnectionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionField, value) != true)) {
                    this.ConnectionField = value;
                    this.RaisePropertyChanged("Connection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TerminalID {
            get {
                return this.TerminalIDField;
            }
            set {
                if ((this.TerminalIDField.Equals(value) != true)) {
                    this.TerminalIDField = value;
                    this.RaisePropertyChanged("TerminalID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigurationFault", Namespace="http://schemas.datacontract.org/2004/07/Argix")]
    [System.SerializableAttribute()]
    public partial class ConfigurationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserConfiguration", Namespace="http://schemas.datacontract.org/2004/07/Argix", ItemName="KeyValueOfstringstring", KeyName="Key", ValueName="Value")]
    [System.SerializableAttribute()]
    public class UserConfiguration : System.Collections.Generic.Dictionary<string, string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TraceMessage", Namespace="http://schemas.datacontract.org/2004/07/Argix")]
    [System.SerializableAttribute()]
    public partial class TraceMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComputerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Keyword1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Keyword2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Keyword3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Argix.HR.LogLevel LogLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Computer {
            get {
                return this.ComputerField;
            }
            set {
                if ((object.ReferenceEquals(this.ComputerField, value) != true)) {
                    this.ComputerField = value;
                    this.RaisePropertyChanged("Computer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Event {
            get {
                return this.EventField;
            }
            set {
                if ((object.ReferenceEquals(this.EventField, value) != true)) {
                    this.EventField = value;
                    this.RaisePropertyChanged("Event");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keyword1 {
            get {
                return this.Keyword1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Keyword1Field, value) != true)) {
                    this.Keyword1Field = value;
                    this.RaisePropertyChanged("Keyword1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keyword2 {
            get {
                return this.Keyword2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Keyword2Field, value) != true)) {
                    this.Keyword2Field = value;
                    this.RaisePropertyChanged("Keyword2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keyword3 {
            get {
                return this.Keyword3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Keyword3Field, value) != true)) {
                    this.Keyword3Field = value;
                    this.RaisePropertyChanged("Keyword3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Argix.HR.LogLevel LogLevel {
            get {
                return this.LogLevelField;
            }
            set {
                if ((this.LogLevelField.Equals(value) != true)) {
                    this.LogLevelField = value;
                    this.RaisePropertyChanged("LogLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogLevel", Namespace="http://schemas.datacontract.org/2004/07/Argix")]
    public enum LogLevel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Debug = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
    [System.SerializableAttribute()]
    public partial class HRFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Badge", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Argix.HR.EmployeeBadge))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Argix.HR.VendorBadge))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Argix.HR.DriverBadge))]
    public partial class Badge : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BadgeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasPhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasSignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HireDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StatusDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuffixField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BadgeNumber {
            get {
                return this.BadgeNumberField;
            }
            set {
                if ((this.BadgeNumberField.Equals(value) != true)) {
                    this.BadgeNumberField = value;
                    this.RaisePropertyChanged("BadgeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool HasPhoto {
            get {
                return this.HasPhotoField;
            }
            set {
                if ((this.HasPhotoField.Equals(value) != true)) {
                    this.HasPhotoField = value;
                    this.RaisePropertyChanged("HasPhoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool HasSignature {
            get {
                return this.HasSignatureField;
            }
            set {
                if ((this.HasSignatureField.Equals(value) != true)) {
                    this.HasSignatureField = value;
                    this.RaisePropertyChanged("HasSignature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime HireDate {
            get {
                return this.HireDateField;
            }
            set {
                if ((this.HireDateField.Equals(value) != true)) {
                    this.HireDateField = value;
                    this.RaisePropertyChanged("HireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDNumber {
            get {
                return this.IDNumberField;
            }
            set {
                if ((this.IDNumberField.Equals(value) != true)) {
                    this.IDNumberField = value;
                    this.RaisePropertyChanged("IDNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssueDate {
            get {
                return this.IssueDateField;
            }
            set {
                if ((this.IssueDateField.Equals(value) != true)) {
                    this.IssueDateField = value;
                    this.RaisePropertyChanged("IssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Middle {
            get {
                return this.MiddleField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleField, value) != true)) {
                    this.MiddleField = value;
                    this.RaisePropertyChanged("Middle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime StatusDate {
            get {
                return this.StatusDateField;
            }
            set {
                if ((this.StatusDateField.Equals(value) != true)) {
                    this.StatusDateField = value;
                    this.RaisePropertyChanged("StatusDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Suffix {
            get {
                return this.SuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.SuffixField, value) != true)) {
                    this.SuffixField = value;
                    this.RaisePropertyChanged("Suffix");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeBadge", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
    [System.SerializableAttribute()]
    public partial class EmployeeBadge : Argix.HR.Badge {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FaccodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubLocationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int Faccode {
            get {
                return this.FaccodeField;
            }
            set {
                if ((this.FaccodeField.Equals(value) != true)) {
                    this.FaccodeField = value;
                    this.RaisePropertyChanged("Faccode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SSN {
            get {
                return this.SSNField;
            }
            set {
                if ((object.ReferenceEquals(this.SSNField, value) != true)) {
                    this.SSNField = value;
                    this.RaisePropertyChanged("SSN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubLocation {
            get {
                return this.SubLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.SubLocationField, value) != true)) {
                    this.SubLocationField = value;
                    this.RaisePropertyChanged("SubLocation");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VendorBadge", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
    [System.SerializableAttribute()]
    public partial class VendorBadge : Argix.HR.Badge {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DriverBadge", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
    [System.SerializableAttribute()]
    public partial class DriverBadge : Argix.HR.Badge {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FaccodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubLocationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int Faccode {
            get {
                return this.FaccodeField;
            }
            set {
                if ((this.FaccodeField.Equals(value) != true)) {
                    this.FaccodeField = value;
                    this.RaisePropertyChanged("Faccode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubLocation {
            get {
                return this.SubLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.SubLocationField, value) != true)) {
                    this.SubLocationField = value;
                    this.RaisePropertyChanged("SubLocation");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Argix.HR", ConfigurationName="HR.IBadgeService")]
    public interface IBadgeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IBadgeService/GetServiceInfo", ReplyAction="http://Argix.HR/IBadgeService/GetServiceInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.ConfigurationFault), Action="http://Argix.ConfigurationFault", Name="ConfigurationFault", Namespace="http://schemas.datacontract.org/2004/07/Argix")]
        Argix.HR.ServiceInfo GetServiceInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IBadgeService/GetUserConfiguration", ReplyAction="http://Argix.HR/IBadgeService/GetUserConfigurationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.ConfigurationFault), Action="http://Argix.ConfigurationFault", Name="ConfigurationFault", Namespace="http://schemas.datacontract.org/2004/07/Argix")]
        Argix.HR.UserConfiguration GetUserConfiguration(string application, string[] usernames);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Argix.HR/IBadgeService/WriteLogEntry")]
        void WriteLogEntry(Argix.HR.TraceMessage m);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBadgeServiceChannel : Argix.HR.IBadgeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BadgeServiceClient : System.ServiceModel.ClientBase<Argix.HR.IBadgeService>, Argix.HR.IBadgeService {
        
        public BadgeServiceClient() {
        }
        
        public BadgeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BadgeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BadgeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BadgeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Argix.HR.ServiceInfo GetServiceInfo() {
            return base.Channel.GetServiceInfo();
        }
        
        public Argix.HR.UserConfiguration GetUserConfiguration(string application, string[] usernames) {
            return base.Channel.GetUserConfiguration(application, usernames);
        }
        
        public void WriteLogEntry(Argix.HR.TraceMessage m) {
            base.Channel.WriteLogEntry(m);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Argix.HR", ConfigurationName="HR.IAccessControlBadgeService")]
    public interface IAccessControlBadgeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IAccessControlBadgeService/ViewAccessControlBadges", ReplyAction="http://Argix.HR/IAccessControlBadgeService/ViewAccessControlBadgesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet ViewAccessControlBadges();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccessControlBadgeServiceChannel : Argix.HR.IAccessControlBadgeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessControlBadgeServiceClient : System.ServiceModel.ClientBase<Argix.HR.IAccessControlBadgeService>, Argix.HR.IAccessControlBadgeService {
        
        public AccessControlBadgeServiceClient() {
        }
        
        public AccessControlBadgeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessControlBadgeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessControlBadgeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessControlBadgeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ViewAccessControlBadges() {
            return base.Channel.ViewAccessControlBadges();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Argix.HR", ConfigurationName="HR.IDriverBadgeService")]
    public interface IDriverBadgeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IDriverBadgeService/ViewDriverBadges", ReplyAction="http://Argix.HR/IDriverBadgeService/ViewDriverBadgesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet ViewDriverBadges();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IDriverBadgeService/ViewDriverBadgesSummary", ReplyAction="http://Argix.HR/IDriverBadgeService/ViewDriverBadgesSummaryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet ViewDriverBadgesSummary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IDriverBadgeService/GetDriverBadge", ReplyAction="http://Argix.HR/IDriverBadgeService/GetDriverBadgeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        Argix.HR.DriverBadge GetDriverBadge(int idNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IDriverBadgeService/SearchDriverBadges", ReplyAction="http://Argix.HR/IDriverBadgeService/SearchDriverBadgesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet SearchDriverBadges(string lastName, string firstName, string location, string badgeNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDriverBadgeServiceChannel : Argix.HR.IDriverBadgeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DriverBadgeServiceClient : System.ServiceModel.ClientBase<Argix.HR.IDriverBadgeService>, Argix.HR.IDriverBadgeService {
        
        public DriverBadgeServiceClient() {
        }
        
        public DriverBadgeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DriverBadgeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DriverBadgeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DriverBadgeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ViewDriverBadges() {
            return base.Channel.ViewDriverBadges();
        }
        
        public System.Data.DataSet ViewDriverBadgesSummary() {
            return base.Channel.ViewDriverBadgesSummary();
        }
        
        public Argix.HR.DriverBadge GetDriverBadge(int idNumber) {
            return base.Channel.GetDriverBadge(idNumber);
        }
        
        public System.Data.DataSet SearchDriverBadges(string lastName, string firstName, string location, string badgeNumber) {
            return base.Channel.SearchDriverBadges(lastName, firstName, location, badgeNumber);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Argix.HR", ConfigurationName="HR.IEmployeeBadgeService")]
    public interface IEmployeeBadgeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IEmployeeBadgeService/ViewEmployeeBadges", ReplyAction="http://Argix.HR/IEmployeeBadgeService/ViewEmployeeBadgesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet ViewEmployeeBadges();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IEmployeeBadgeService/ViewEmployeeBadgesSummary", ReplyAction="http://Argix.HR/IEmployeeBadgeService/ViewEmployeeBadgesSummaryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet ViewEmployeeBadgesSummary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IEmployeeBadgeService/GetEmployeeBadge", ReplyAction="http://Argix.HR/IEmployeeBadgeService/GetEmployeeBadgeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        Argix.HR.EmployeeBadge GetEmployeeBadge(int idNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IEmployeeBadgeService/AddEmployeeBadge", ReplyAction="http://Argix.HR/IEmployeeBadgeService/AddEmployeeBadgeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        bool AddEmployeeBadge(Argix.HR.EmployeeBadge badge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IEmployeeBadgeService/UpdateEmployeeBadge", ReplyAction="http://Argix.HR/IEmployeeBadgeService/UpdateEmployeeBadgeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        bool UpdateEmployeeBadge(Argix.HR.EmployeeBadge badge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IEmployeeBadgeService/SearchEmployeeBadges", ReplyAction="http://Argix.HR/IEmployeeBadgeService/SearchEmployeeBadgesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet SearchEmployeeBadges(string lastName, string firstName, string location, string badgeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IEmployeeBadgeService/GetEmployeeDepartmentList", ReplyAction="http://Argix.HR/IEmployeeBadgeService/GetEmployeeDepartmentListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet GetEmployeeDepartmentList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IEmployeeBadgeService/GetEmployeeLocationList", ReplyAction="http://Argix.HR/IEmployeeBadgeService/GetEmployeeLocationListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet GetEmployeeLocationList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IEmployeeBadgeService/GetEmployeeSubLocationList", ReplyAction="http://Argix.HR/IEmployeeBadgeService/GetEmployeeSubLocationListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet GetEmployeeSubLocationList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IEmployeeBadgeService/GetEmployeeStatusList", ReplyAction="http://Argix.HR/IEmployeeBadgeService/GetEmployeeStatusListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet GetEmployeeStatusList();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeBadgeServiceChannel : Argix.HR.IEmployeeBadgeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeBadgeServiceClient : System.ServiceModel.ClientBase<Argix.HR.IEmployeeBadgeService>, Argix.HR.IEmployeeBadgeService {
        
        public EmployeeBadgeServiceClient() {
        }
        
        public EmployeeBadgeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeBadgeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeBadgeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeBadgeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ViewEmployeeBadges() {
            return base.Channel.ViewEmployeeBadges();
        }
        
        public System.Data.DataSet ViewEmployeeBadgesSummary() {
            return base.Channel.ViewEmployeeBadgesSummary();
        }
        
        public Argix.HR.EmployeeBadge GetEmployeeBadge(int idNumber) {
            return base.Channel.GetEmployeeBadge(idNumber);
        }
        
        public bool AddEmployeeBadge(Argix.HR.EmployeeBadge badge) {
            return base.Channel.AddEmployeeBadge(badge);
        }
        
        public bool UpdateEmployeeBadge(Argix.HR.EmployeeBadge badge) {
            return base.Channel.UpdateEmployeeBadge(badge);
        }
        
        public System.Data.DataSet SearchEmployeeBadges(string lastName, string firstName, string location, string badgeNumber) {
            return base.Channel.SearchEmployeeBadges(lastName, firstName, location, badgeNumber);
        }
        
        public System.Data.DataSet GetEmployeeDepartmentList() {
            return base.Channel.GetEmployeeDepartmentList();
        }
        
        public System.Data.DataSet GetEmployeeLocationList() {
            return base.Channel.GetEmployeeLocationList();
        }
        
        public System.Data.DataSet GetEmployeeSubLocationList() {
            return base.Channel.GetEmployeeSubLocationList();
        }
        
        public System.Data.DataSet GetEmployeeStatusList() {
            return base.Channel.GetEmployeeStatusList();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Argix.HR", ConfigurationName="HR.IVendorBadgeService")]
    public interface IVendorBadgeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IVendorBadgeService/ViewVendorBadges", ReplyAction="http://Argix.HR/IVendorBadgeService/ViewVendorBadgesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet ViewVendorBadges();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IVendorBadgeService/ViewVendorBadgesSummary", ReplyAction="http://Argix.HR/IVendorBadgeService/ViewVendorBadgesSummaryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet ViewVendorBadgesSummary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IVendorBadgeService/GetVendorBadge", ReplyAction="http://Argix.HR/IVendorBadgeService/GetVendorBadgeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        Argix.HR.VendorBadge GetVendorBadge(int idNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IVendorBadgeService/AddVendorBadge", ReplyAction="http://Argix.HR/IVendorBadgeService/AddVendorBadgeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        bool AddVendorBadge(Argix.HR.VendorBadge badge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IVendorBadgeService/UpdateVendorBadge", ReplyAction="http://Argix.HR/IVendorBadgeService/UpdateVendorBadgeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        bool UpdateVendorBadge(Argix.HR.VendorBadge badge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IVendorBadgeService/SearchVendorBadges", ReplyAction="http://Argix.HR/IVendorBadgeService/SearchVendorBadgesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet SearchVendorBadges(string lastName, string firstName, string location, string badgeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IVendorBadgeService/GetVendorDepartmentList", ReplyAction="http://Argix.HR/IVendorBadgeService/GetVendorDepartmentListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet GetVendorDepartmentList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IVendorBadgeService/GetVendorLocationList", ReplyAction="http://Argix.HR/IVendorBadgeService/GetVendorLocationListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet GetVendorLocationList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.HR/IVendorBadgeService/GetVendorStatusList", ReplyAction="http://Argix.HR/IVendorBadgeService/GetVendorStatusListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.HR.HRFault), Action="http://Argix.HR.HRFault", Name="HRFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.HR")]
        System.Data.DataSet GetVendorStatusList();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVendorBadgeServiceChannel : Argix.HR.IVendorBadgeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VendorBadgeServiceClient : System.ServiceModel.ClientBase<Argix.HR.IVendorBadgeService>, Argix.HR.IVendorBadgeService {
        
        public VendorBadgeServiceClient() {
        }
        
        public VendorBadgeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VendorBadgeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendorBadgeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendorBadgeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ViewVendorBadges() {
            return base.Channel.ViewVendorBadges();
        }
        
        public System.Data.DataSet ViewVendorBadgesSummary() {
            return base.Channel.ViewVendorBadgesSummary();
        }
        
        public Argix.HR.VendorBadge GetVendorBadge(int idNumber) {
            return base.Channel.GetVendorBadge(idNumber);
        }
        
        public bool AddVendorBadge(Argix.HR.VendorBadge badge) {
            return base.Channel.AddVendorBadge(badge);
        }
        
        public bool UpdateVendorBadge(Argix.HR.VendorBadge badge) {
            return base.Channel.UpdateVendorBadge(badge);
        }
        
        public System.Data.DataSet SearchVendorBadges(string lastName, string firstName, string location, string badgeNumber) {
            return base.Channel.SearchVendorBadges(lastName, firstName, location, badgeNumber);
        }
        
        public System.Data.DataSet GetVendorDepartmentList() {
            return base.Channel.GetVendorDepartmentList();
        }
        
        public System.Data.DataSet GetVendorLocationList() {
            return base.Channel.GetVendorLocationList();
        }
        
        public System.Data.DataSet GetVendorStatusList() {
            return base.Channel.GetVendorStatusList();
        }
    }
}
