//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace Argix.Finance {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Detail : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        internal Microsoft.Office.Tools.Excel.NamedRange BillToAttention;
        
        internal Microsoft.Office.Tools.Excel.NamedRange BillToName;
        
        internal Microsoft.Office.Tools.Excel.NamedRange BillToAddressLine1;
        
        internal Microsoft.Office.Tools.Excel.NamedRange BillToCityStateZip;
        
        internal Microsoft.Office.Tools.Excel.NamedRange RemitToName;
        
        internal Microsoft.Office.Tools.Excel.NamedRange RemitToAddressLine1;
        
        internal Microsoft.Office.Tools.Excel.NamedRange RemitToCityStateZip;
        
        internal Microsoft.Office.Tools.Excel.NamedRange InvoiceDate;
        
        internal Microsoft.Office.Tools.Excel.NamedRange InvoiceNumber;
        
        internal Microsoft.Office.Tools.Excel.NamedRange InvoiceAmount;
        
        internal Microsoft.Office.Tools.Excel.NamedRange AccountNumber;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Terms;
        
        internal Microsoft.Office.Tools.Excel.NamedRange ServicePeriod;
        
        internal Microsoft.Office.Tools.Excel.NamedRange PhoneNumber;
        
        internal Microsoft.Office.Tools.Excel.NamedRange FuelPrice;
        
        internal Microsoft.Office.Tools.Excel.NamedRange FuelCharge;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Email1;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Email2;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet2_Print_Area;
        
        internal Microsoft.Office.Tools.Excel.NamedRange FuelChargeD;
        
        internal Microsoft.Office.Tools.Excel.NamedRange FuelPriceD;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Detail(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet2", "Sheet2") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Detail = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.BillToAttention.BeginInit();
            this.BillToName.BeginInit();
            this.BillToAddressLine1.BeginInit();
            this.BillToCityStateZip.BeginInit();
            this.RemitToName.BeginInit();
            this.RemitToAddressLine1.BeginInit();
            this.RemitToCityStateZip.BeginInit();
            this.InvoiceDate.BeginInit();
            this.InvoiceNumber.BeginInit();
            this.InvoiceAmount.BeginInit();
            this.AccountNumber.BeginInit();
            this.Terms.BeginInit();
            this.ServicePeriod.BeginInit();
            this.PhoneNumber.BeginInit();
            this.FuelPrice.BeginInit();
            this.FuelCharge.BeginInit();
            this.Email1.BeginInit();
            this.Email2.BeginInit();
            this.Sheet2_Print_Area.BeginInit();
            this.FuelChargeD.BeginInit();
            this.FuelPriceD.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.FuelPriceD.EndInit();
            this.FuelChargeD.EndInit();
            this.Sheet2_Print_Area.EndInit();
            this.Email2.EndInit();
            this.Email1.EndInit();
            this.FuelCharge.EndInit();
            this.FuelPrice.EndInit();
            this.PhoneNumber.EndInit();
            this.ServicePeriod.EndInit();
            this.Terms.EndInit();
            this.AccountNumber.EndInit();
            this.InvoiceAmount.EndInit();
            this.InvoiceNumber.EndInit();
            this.InvoiceDate.EndInit();
            this.RemitToCityStateZip.EndInit();
            this.RemitToAddressLine1.EndInit();
            this.RemitToName.EndInit();
            this.BillToCityStateZip.EndInit();
            this.BillToAddressLine1.EndInit();
            this.BillToName.EndInit();
            this.BillToAttention.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.BillToAttention = Globals.Factory.CreateNamedRange(null, null, "BillToAttention", "BillToAttention", this);
            this.BillToName = Globals.Factory.CreateNamedRange(null, null, "BillToName", "BillToName", this);
            this.BillToAddressLine1 = Globals.Factory.CreateNamedRange(null, null, "BillToAddressLine1", "BillToAddressLine1", this);
            this.BillToCityStateZip = Globals.Factory.CreateNamedRange(null, null, "BillToCityStateZip", "BillToCityStateZip", this);
            this.RemitToName = Globals.Factory.CreateNamedRange(null, null, "RemitToName", "RemitToName", this);
            this.RemitToAddressLine1 = Globals.Factory.CreateNamedRange(null, null, "RemitToAddressLine1", "RemitToAddressLine1", this);
            this.RemitToCityStateZip = Globals.Factory.CreateNamedRange(null, null, "RemitToCityStateZip", "RemitToCityStateZip", this);
            this.InvoiceDate = Globals.Factory.CreateNamedRange(null, null, "InvoiceDate", "InvoiceDate", this);
            this.InvoiceNumber = Globals.Factory.CreateNamedRange(null, null, "InvoiceNumber", "InvoiceNumber", this);
            this.InvoiceAmount = Globals.Factory.CreateNamedRange(null, null, "InvoiceAmount", "InvoiceAmount", this);
            this.AccountNumber = Globals.Factory.CreateNamedRange(null, null, "AccountNumber", "AccountNumber", this);
            this.Terms = Globals.Factory.CreateNamedRange(null, null, "Terms", "Terms", this);
            this.ServicePeriod = Globals.Factory.CreateNamedRange(null, null, "ServicePeriod", "ServicePeriod", this);
            this.PhoneNumber = Globals.Factory.CreateNamedRange(null, null, "PhoneNumber", "PhoneNumber", this);
            this.FuelPrice = Globals.Factory.CreateNamedRange(null, null, "FuelPrice", "FuelPrice", this);
            this.FuelCharge = Globals.Factory.CreateNamedRange(null, null, "FuelCharge", "FuelCharge", this);
            this.Email1 = Globals.Factory.CreateNamedRange(null, null, "Email1", "Email1", this);
            this.Email2 = Globals.Factory.CreateNamedRange(null, null, "Email2", "Email2", this);
            this.Sheet2_Print_Area = Globals.Factory.CreateNamedRange(null, null, "Sheet2!Print_Area", "Sheet2_Print_Area", this);
            this.FuelChargeD = Globals.Factory.CreateNamedRange(null, null, "FuelChargeD", "FuelChargeD", this);
            this.FuelPriceD = Globals.Factory.CreateNamedRange(null, null, "FuelPriceD", "FuelPriceD", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // BillToAttention
            // 
            this.BillToAttention.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // BillToName
            // 
            this.BillToName.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // BillToAddressLine1
            // 
            this.BillToAddressLine1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // BillToCityStateZip
            // 
            this.BillToCityStateZip.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // RemitToName
            // 
            this.RemitToName.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // RemitToAddressLine1
            // 
            this.RemitToAddressLine1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // RemitToCityStateZip
            // 
            this.RemitToCityStateZip.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // InvoiceDate
            // 
            this.InvoiceDate.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // InvoiceNumber
            // 
            this.InvoiceNumber.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // InvoiceAmount
            // 
            this.InvoiceAmount.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // AccountNumber
            // 
            this.AccountNumber.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Terms
            // 
            this.Terms.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // ServicePeriod
            // 
            this.ServicePeriod.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // PhoneNumber
            // 
            this.PhoneNumber.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // FuelPrice
            // 
            this.FuelPrice.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // FuelCharge
            // 
            this.FuelCharge.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Email1
            // 
            this.Email1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Email2
            // 
            this.Email2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Sheet2_Print_Area
            // 
            this.Sheet2_Print_Area.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // FuelChargeD
            // 
            this.FuelChargeD.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // FuelPriceD
            // 
            this.FuelPriceD.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Detail
            // 
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.FuelPriceD.Dispose();
            this.FuelChargeD.Dispose();
            this.Sheet2_Print_Area.Dispose();
            this.Email2.Dispose();
            this.Email1.Dispose();
            this.FuelCharge.Dispose();
            this.FuelPrice.Dispose();
            this.PhoneNumber.Dispose();
            this.ServicePeriod.Dispose();
            this.Terms.Dispose();
            this.AccountNumber.Dispose();
            this.InvoiceAmount.Dispose();
            this.InvoiceNumber.Dispose();
            this.InvoiceDate.Dispose();
            this.RemitToCityStateZip.Dispose();
            this.RemitToAddressLine1.Dispose();
            this.RemitToName.Dispose();
            this.BillToCityStateZip.Dispose();
            this.BillToAddressLine1.Dispose();
            this.BillToName.Dispose();
            this.BillToAttention.Dispose();
            base.OnShutdown();
        }
    }
    
    internal sealed partial class Globals {
        
        private static Detail _Detail;
        
        internal static Detail Detail {
            get {
                return _Detail;
            }
            set {
                if ((_Detail == null)) {
                    _Detail = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
