//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argix.Terminals {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceInfo", Namespace="http://schemas.datacontract.org/2004/07/Argix")]
    [System.SerializableAttribute()]
    public partial class ServiceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TerminalIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Connection {
            get {
                return this.ConnectionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionField, value) != true)) {
                    this.ConnectionField = value;
                    this.RaisePropertyChanged("Connection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TerminalID {
            get {
                return this.TerminalIDField;
            }
            set {
                if ((this.TerminalIDField.Equals(value) != true)) {
                    this.TerminalIDField = value;
                    this.RaisePropertyChanged("TerminalID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigurationFault", Namespace="http://schemas.datacontract.org/2004/07/Argix")]
    [System.SerializableAttribute()]
    public partial class ConfigurationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserConfiguration", Namespace="http://schemas.datacontract.org/2004/07/Argix", ItemName="KeyValueOfstringstring", KeyName="Key", ValueName="Value")]
    [System.SerializableAttribute()]
    public class UserConfiguration : System.Collections.Generic.Dictionary<string, string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TraceMessage", Namespace="http://schemas.datacontract.org/2004/07/Argix")]
    [System.SerializableAttribute()]
    public partial class TraceMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComputerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Keyword1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Keyword2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Keyword3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Argix.Terminals.LogLevel LogLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Computer {
            get {
                return this.ComputerField;
            }
            set {
                if ((object.ReferenceEquals(this.ComputerField, value) != true)) {
                    this.ComputerField = value;
                    this.RaisePropertyChanged("Computer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Event {
            get {
                return this.EventField;
            }
            set {
                if ((object.ReferenceEquals(this.EventField, value) != true)) {
                    this.EventField = value;
                    this.RaisePropertyChanged("Event");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keyword1 {
            get {
                return this.Keyword1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Keyword1Field, value) != true)) {
                    this.Keyword1Field = value;
                    this.RaisePropertyChanged("Keyword1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keyword2 {
            get {
                return this.Keyword2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Keyword2Field, value) != true)) {
                    this.Keyword2Field = value;
                    this.RaisePropertyChanged("Keyword2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keyword3 {
            get {
                return this.Keyword3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Keyword3Field, value) != true)) {
                    this.Keyword3Field = value;
                    this.RaisePropertyChanged("Keyword3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Argix.Terminals.LogLevel LogLevel {
            get {
                return this.LogLevelField;
            }
            set {
                if ((this.LogLevelField.Equals(value) != true)) {
                    this.LogLevelField = value;
                    this.RaisePropertyChanged("LogLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogLevel", Namespace="http://schemas.datacontract.org/2004/07/Argix")]
    public enum LogLevel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Debug = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
    [System.SerializableAttribute()]
    public partial class RoadshowFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pickup", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
    [System.SerializableAttribute()]
    public partial class Pickup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActualCommodityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ActualOrderSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ActualOrderWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlannedCommodityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PlannedOrderCubeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PlannedOrderSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PlannedOrderWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ReturnTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RouteDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RouteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnscheduledPickupField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActualCommodity {
            get {
                return this.ActualCommodityField;
            }
            set {
                if ((object.ReferenceEquals(this.ActualCommodityField, value) != true)) {
                    this.ActualCommodityField = value;
                    this.RaisePropertyChanged("ActualCommodity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ActualOrderSize {
            get {
                return this.ActualOrderSizeField;
            }
            set {
                if ((this.ActualOrderSizeField.Equals(value) != true)) {
                    this.ActualOrderSizeField = value;
                    this.RaisePropertyChanged("ActualOrderSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ActualOrderWeight {
            get {
                return this.ActualOrderWeightField;
            }
            set {
                if ((this.ActualOrderWeightField.Equals(value) != true)) {
                    this.ActualOrderWeightField = value;
                    this.RaisePropertyChanged("ActualOrderWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAddress {
            get {
                return this.CustomerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressField, value) != true)) {
                    this.CustomerAddressField = value;
                    this.RaisePropertyChanged("CustomerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCity {
            get {
                return this.CustomerCityField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCityField, value) != true)) {
                    this.CustomerCityField = value;
                    this.RaisePropertyChanged("CustomerCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerState {
            get {
                return this.CustomerStateField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerStateField, value) != true)) {
                    this.CustomerStateField = value;
                    this.RaisePropertyChanged("CustomerState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerType {
            get {
                return this.CustomerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTypeField, value) != true)) {
                    this.CustomerTypeField = value;
                    this.RaisePropertyChanged("CustomerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerZip {
            get {
                return this.CustomerZipField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerZipField, value) != true)) {
                    this.CustomerZipField = value;
                    this.RaisePropertyChanged("CustomerZip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Depot {
            get {
                return this.DepotField;
            }
            set {
                if ((object.ReferenceEquals(this.DepotField, value) != true)) {
                    this.DepotField = value;
                    this.RaisePropertyChanged("Depot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Driver {
            get {
                return this.DriverField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverField, value) != true)) {
                    this.DriverField = value;
                    this.RaisePropertyChanged("Driver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderType {
            get {
                return this.OrderTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderTypeField, value) != true)) {
                    this.OrderTypeField = value;
                    this.RaisePropertyChanged("OrderType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlannedCommodity {
            get {
                return this.PlannedCommodityField;
            }
            set {
                if ((object.ReferenceEquals(this.PlannedCommodityField, value) != true)) {
                    this.PlannedCommodityField = value;
                    this.RaisePropertyChanged("PlannedCommodity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PlannedOrderCube {
            get {
                return this.PlannedOrderCubeField;
            }
            set {
                if ((this.PlannedOrderCubeField.Equals(value) != true)) {
                    this.PlannedOrderCubeField = value;
                    this.RaisePropertyChanged("PlannedOrderCube");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PlannedOrderSize {
            get {
                return this.PlannedOrderSizeField;
            }
            set {
                if ((this.PlannedOrderSizeField.Equals(value) != true)) {
                    this.PlannedOrderSizeField = value;
                    this.RaisePropertyChanged("PlannedOrderSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PlannedOrderWeight {
            get {
                return this.PlannedOrderWeightField;
            }
            set {
                if ((this.PlannedOrderWeightField.Equals(value) != true)) {
                    this.PlannedOrderWeightField = value;
                    this.RaisePropertyChanged("PlannedOrderWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordID {
            get {
                return this.RecordIDField;
            }
            set {
                if ((this.RecordIDField.Equals(value) != true)) {
                    this.RecordIDField = value;
                    this.RaisePropertyChanged("RecordID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ReturnTime {
            get {
                return this.ReturnTimeField;
            }
            set {
                if ((this.ReturnTimeField.Equals(value) != true)) {
                    this.ReturnTimeField = value;
                    this.RaisePropertyChanged("ReturnTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RouteDate {
            get {
                return this.RouteDateField;
            }
            set {
                if ((this.RouteDateField.Equals(value) != true)) {
                    this.RouteDateField = value;
                    this.RaisePropertyChanged("RouteDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RouteName {
            get {
                return this.RouteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RouteNameField, value) != true)) {
                    this.RouteNameField = value;
                    this.RaisePropertyChanged("RouteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnscheduledPickup {
            get {
                return this.UnscheduledPickupField;
            }
            set {
                if ((object.ReferenceEquals(this.UnscheduledPickupField, value) != true)) {
                    this.UnscheduledPickupField = value;
                    this.RaisePropertyChanged("UnscheduledPickup");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Pickups", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals", ItemName="Pickup")]
    [System.SerializableAttribute()]
    public class Pickups : System.Collections.Generic.List<Argix.Terminals.Pickup> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ScanAudits", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals", ItemName="ScanAudit")]
    [System.SerializableAttribute()]
    public class ScanAudits : System.Collections.Generic.List<Argix.Terminals.ScanAudit> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScanAudit", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
    [System.SerializableAttribute()]
    public partial class ScanAudit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalCommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArriveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CRGResolutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CRGStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartonsScannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommodityClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommodityDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntryByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MallBuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OnTimeIssueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short OrderCloseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short OrderOpenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PiecesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PlannedArrivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PlannedDepartureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RouteClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RouteDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RouteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RouteSequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RouteSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScanIssueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScanUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeEntryByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short TripField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short TripStopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short WaitMinimumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalComments {
            get {
                return this.AdditionalCommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalCommentsField, value) != true)) {
                    this.AdditionalCommentsField = value;
                    this.RaisePropertyChanged("AdditionalComments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Arrive {
            get {
                return this.ArriveField;
            }
            set {
                if ((object.ReferenceEquals(this.ArriveField, value) != true)) {
                    this.ArriveField = value;
                    this.RaisePropertyChanged("Arrive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bell {
            get {
                return this.BellField;
            }
            set {
                if ((object.ReferenceEquals(this.BellField, value) != true)) {
                    this.BellField = value;
                    this.RaisePropertyChanged("Bell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRGResolution {
            get {
                return this.CRGResolutionField;
            }
            set {
                if ((object.ReferenceEquals(this.CRGResolutionField, value) != true)) {
                    this.CRGResolutionField = value;
                    this.RaisePropertyChanged("CRGResolution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRGStatus {
            get {
                return this.CRGStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.CRGStatusField, value) != true)) {
                    this.CRGStatusField = value;
                    this.RaisePropertyChanged("CRGStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartonsScanned {
            get {
                return this.CartonsScannedField;
            }
            set {
                if ((this.CartonsScannedField.Equals(value) != true)) {
                    this.CartonsScannedField = value;
                    this.RaisePropertyChanged("CartonsScanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommodityClass {
            get {
                return this.CommodityClassField;
            }
            set {
                if ((object.ReferenceEquals(this.CommodityClassField, value) != true)) {
                    this.CommodityClassField = value;
                    this.RaisePropertyChanged("CommodityClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommodityDescription {
            get {
                return this.CommodityDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CommodityDescriptionField, value) != true)) {
                    this.CommodityDescriptionField = value;
                    this.RaisePropertyChanged("CommodityDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAccount {
            get {
                return this.CustomerAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAccountField, value) != true)) {
                    this.CustomerAccountField = value;
                    this.RaisePropertyChanged("CustomerAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryEnd {
            get {
                return this.DeliveryEndField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryEndField, value) != true)) {
                    this.DeliveryEndField = value;
                    this.RaisePropertyChanged("DeliveryEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryStart {
            get {
                return this.DeliveryStartField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryStartField, value) != true)) {
                    this.DeliveryStartField = value;
                    this.RaisePropertyChanged("DeliveryStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departure {
            get {
                return this.DepartureField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureField, value) != true)) {
                    this.DepartureField = value;
                    this.RaisePropertyChanged("Departure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Driver {
            get {
                return this.DriverField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverField, value) != true)) {
                    this.DriverField = value;
                    this.RaisePropertyChanged("Driver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntryBy {
            get {
                return this.EntryByField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryByField, value) != true)) {
                    this.EntryByField = value;
                    this.RaisePropertyChanged("EntryBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MallBuilding {
            get {
                return this.MallBuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.MallBuildingField, value) != true)) {
                    this.MallBuildingField = value;
                    this.RaisePropertyChanged("MallBuilding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OnTimeIssue {
            get {
                return this.OnTimeIssueField;
            }
            set {
                if ((object.ReferenceEquals(this.OnTimeIssueField, value) != true)) {
                    this.OnTimeIssueField = value;
                    this.RaisePropertyChanged("OnTimeIssue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short OrderClose {
            get {
                return this.OrderCloseField;
            }
            set {
                if ((this.OrderCloseField.Equals(value) != true)) {
                    this.OrderCloseField = value;
                    this.RaisePropertyChanged("OrderClose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short OrderOpen {
            get {
                return this.OrderOpenField;
            }
            set {
                if ((this.OrderOpenField.Equals(value) != true)) {
                    this.OrderOpenField = value;
                    this.RaisePropertyChanged("OrderOpen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderType {
            get {
                return this.OrderTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderTypeField, value) != true)) {
                    this.OrderTypeField = value;
                    this.RaisePropertyChanged("OrderType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Payee {
            get {
                return this.PayeeField;
            }
            set {
                if ((object.ReferenceEquals(this.PayeeField, value) != true)) {
                    this.PayeeField = value;
                    this.RaisePropertyChanged("Payee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Pieces {
            get {
                return this.PiecesField;
            }
            set {
                if ((this.PiecesField.Equals(value) != true)) {
                    this.PiecesField = value;
                    this.RaisePropertyChanged("Pieces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short PlannedArrival {
            get {
                return this.PlannedArrivalField;
            }
            set {
                if ((this.PlannedArrivalField.Equals(value) != true)) {
                    this.PlannedArrivalField = value;
                    this.RaisePropertyChanged("PlannedArrival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short PlannedDeparture {
            get {
                return this.PlannedDepartureField;
            }
            set {
                if ((this.PlannedDepartureField.Equals(value) != true)) {
                    this.PlannedDepartureField = value;
                    this.RaisePropertyChanged("PlannedDeparture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordID {
            get {
                return this.RecordIDField;
            }
            set {
                if ((this.RecordIDField.Equals(value) != true)) {
                    this.RecordIDField = value;
                    this.RaisePropertyChanged("RecordID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RouteClass {
            get {
                return this.RouteClassField;
            }
            set {
                if ((object.ReferenceEquals(this.RouteClassField, value) != true)) {
                    this.RouteClassField = value;
                    this.RaisePropertyChanged("RouteClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RouteDate {
            get {
                return this.RouteDateField;
            }
            set {
                if ((this.RouteDateField.Equals(value) != true)) {
                    this.RouteDateField = value;
                    this.RaisePropertyChanged("RouteDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RouteName {
            get {
                return this.RouteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RouteNameField, value) != true)) {
                    this.RouteNameField = value;
                    this.RaisePropertyChanged("RouteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RouteSequence {
            get {
                return this.RouteSequenceField;
            }
            set {
                if ((this.RouteSequenceField.Equals(value) != true)) {
                    this.RouteSequenceField = value;
                    this.RaisePropertyChanged("RouteSequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RouteSet {
            get {
                return this.RouteSetField;
            }
            set {
                if ((object.ReferenceEquals(this.RouteSetField, value) != true)) {
                    this.RouteSetField = value;
                    this.RaisePropertyChanged("RouteSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScanIssue {
            get {
                return this.ScanIssueField;
            }
            set {
                if ((object.ReferenceEquals(this.ScanIssueField, value) != true)) {
                    this.ScanIssueField = value;
                    this.RaisePropertyChanged("ScanIssue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScanUser {
            get {
                return this.ScanUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ScanUserField, value) != true)) {
                    this.ScanUserField = value;
                    this.RaisePropertyChanged("ScanUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeEntryBy {
            get {
                return this.TimeEntryByField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeEntryByField, value) != true)) {
                    this.TimeEntryByField = value;
                    this.RaisePropertyChanged("TimeEntryBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Trip {
            get {
                return this.TripField;
            }
            set {
                if ((this.TripField.Equals(value) != true)) {
                    this.TripField = value;
                    this.RaisePropertyChanged("Trip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short TripStop {
            get {
                return this.TripStopField;
            }
            set {
                if ((this.TripStopField.Equals(value) != true)) {
                    this.TripStopField = value;
                    this.RaisePropertyChanged("TripStop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Updated {
            get {
                return this.UpdatedField;
            }
            set {
                if ((this.UpdatedField.Equals(value) != true)) {
                    this.UpdatedField = value;
                    this.RaisePropertyChanged("Updated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short WaitMinimum {
            get {
                return this.WaitMinimumField;
            }
            set {
                if ((this.WaitMinimumField.Equals(value) != true)) {
                    this.WaitMinimumField = value;
                    this.RaisePropertyChanged("WaitMinimum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Argix.Terminals", ConfigurationName="Terminals.IRSReportsService")]
    public interface IRSReportsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/GetServiceInfo", ReplyAction="http://Argix.Terminals/IRSReportsService/GetServiceInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.ConfigurationFault), Action="http://Argix.ConfigurationFault", Name="ConfigurationFault", Namespace="http://schemas.datacontract.org/2004/07/Argix")]
        Argix.Terminals.ServiceInfo GetServiceInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/GetUserConfiguration", ReplyAction="http://Argix.Terminals/IRSReportsService/GetUserConfigurationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.ConfigurationFault), Action="http://Argix.ConfigurationFault", Name="ConfigurationFault", Namespace="http://schemas.datacontract.org/2004/07/Argix")]
        Argix.Terminals.UserConfiguration GetUserConfiguration(string application, string[] usernames);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Argix.Terminals/IRSReportsService/WriteLogEntry")]
        void WriteLogEntry(Argix.Terminals.TraceMessage m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/LoadPickups", ReplyAction="http://Argix.Terminals/IRSReportsService/LoadPickupsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        bool LoadPickups(System.DateTime pickupDate, string routeClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/ReadPickups", ReplyAction="http://Argix.Terminals/IRSReportsService/ReadPickupsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        System.Data.DataSet ReadPickups(System.DateTime pickupDate, string routeClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/AddPickup", ReplyAction="http://Argix.Terminals/IRSReportsService/AddPickupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        bool AddPickup(Argix.Terminals.Pickup pickup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/UpdatePickups", ReplyAction="http://Argix.Terminals/IRSReportsService/UpdatePickupsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        void UpdatePickups(Argix.Terminals.Pickups pickups);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/UpdatePickup", ReplyAction="http://Argix.Terminals/IRSReportsService/UpdatePickupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        bool UpdatePickup(Argix.Terminals.Pickup pickup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/LoadScanAudits", ReplyAction="http://Argix.Terminals/IRSReportsService/LoadScanAuditsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        bool LoadScanAudits(System.DateTime routeDate, string routeClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/ReadScanAudits", ReplyAction="http://Argix.Terminals/IRSReportsService/ReadScanAuditsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        System.Data.DataSet ReadScanAudits(System.DateTime routeDate, string routeClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/UpdateScanAudits", ReplyAction="http://Argix.Terminals/IRSReportsService/UpdateScanAuditsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        void UpdateScanAudits(Argix.Terminals.ScanAudits audits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/UpdateScanAudit", ReplyAction="http://Argix.Terminals/IRSReportsService/UpdateScanAuditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        bool UpdateScanAudit(Argix.Terminals.ScanAudit audit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/GetCommodityClasses", ReplyAction="http://Argix.Terminals/IRSReportsService/GetCommodityClassesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        System.Data.DataSet GetCommodityClasses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/GetCustomers", ReplyAction="http://Argix.Terminals/IRSReportsService/GetCustomersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        System.Data.DataSet GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/GetDepots", ReplyAction="http://Argix.Terminals/IRSReportsService/GetDepotsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        System.Data.DataSet GetDepots();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/GetDrivers", ReplyAction="http://Argix.Terminals/IRSReportsService/GetDriversResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        System.Data.DataSet GetDrivers(string routeClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/GetOnTimeIssues", ReplyAction="http://Argix.Terminals/IRSReportsService/GetOnTimeIssuesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        System.Data.DataSet GetOnTimeIssues();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/GetOrderTypes", ReplyAction="http://Argix.Terminals/IRSReportsService/GetOrderTypesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        System.Data.DataSet GetOrderTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Argix.Terminals/IRSReportsService/GetUpdateUsers", ReplyAction="http://Argix.Terminals/IRSReportsService/GetUpdateUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Argix.Terminals.RoadshowFault), Action="http://Argix.Terminals.RoadshowFault", Name="RoadshowFault", Namespace="http://schemas.datacontract.org/2004/07/Argix.Terminals")]
        System.Data.DataSet GetUpdateUsers(string routeClass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRSReportsServiceChannel : Argix.Terminals.IRSReportsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RSReportsServiceClient : System.ServiceModel.ClientBase<Argix.Terminals.IRSReportsService>, Argix.Terminals.IRSReportsService {
        
        public RSReportsServiceClient() {
        }
        
        public RSReportsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RSReportsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RSReportsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RSReportsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Argix.Terminals.ServiceInfo GetServiceInfo() {
            return base.Channel.GetServiceInfo();
        }
        
        public Argix.Terminals.UserConfiguration GetUserConfiguration(string application, string[] usernames) {
            return base.Channel.GetUserConfiguration(application, usernames);
        }
        
        public void WriteLogEntry(Argix.Terminals.TraceMessage m) {
            base.Channel.WriteLogEntry(m);
        }
        
        public bool LoadPickups(System.DateTime pickupDate, string routeClass) {
            return base.Channel.LoadPickups(pickupDate, routeClass);
        }
        
        public System.Data.DataSet ReadPickups(System.DateTime pickupDate, string routeClass) {
            return base.Channel.ReadPickups(pickupDate, routeClass);
        }
        
        public bool AddPickup(Argix.Terminals.Pickup pickup) {
            return base.Channel.AddPickup(pickup);
        }
        
        public void UpdatePickups(Argix.Terminals.Pickups pickups) {
            base.Channel.UpdatePickups(pickups);
        }
        
        public bool UpdatePickup(Argix.Terminals.Pickup pickup) {
            return base.Channel.UpdatePickup(pickup);
        }
        
        public bool LoadScanAudits(System.DateTime routeDate, string routeClass) {
            return base.Channel.LoadScanAudits(routeDate, routeClass);
        }
        
        public System.Data.DataSet ReadScanAudits(System.DateTime routeDate, string routeClass) {
            return base.Channel.ReadScanAudits(routeDate, routeClass);
        }
        
        public void UpdateScanAudits(Argix.Terminals.ScanAudits audits) {
            base.Channel.UpdateScanAudits(audits);
        }
        
        public bool UpdateScanAudit(Argix.Terminals.ScanAudit audit) {
            return base.Channel.UpdateScanAudit(audit);
        }
        
        public System.Data.DataSet GetCommodityClasses() {
            return base.Channel.GetCommodityClasses();
        }
        
        public System.Data.DataSet GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Data.DataSet GetDepots() {
            return base.Channel.GetDepots();
        }
        
        public System.Data.DataSet GetDrivers(string routeClass) {
            return base.Channel.GetDrivers(routeClass);
        }
        
        public System.Data.DataSet GetOnTimeIssues() {
            return base.Channel.GetOnTimeIssues();
        }
        
        public System.Data.DataSet GetOrderTypes() {
            return base.Channel.GetOrderTypes();
        }
        
        public System.Data.DataSet GetUpdateUsers(string routeClass) {
            return base.Channel.GetUpdateUsers(routeClass);
        }
    }
}
